# Generated by Django 5.0.6 on 2025-09-19 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.CharField(blank=True, max_length=120)),
                ('season_hint', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RubricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('breakdown', models.JSONField()),
                ('triplet', models.CharField(max_length=20)),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='compose.draft')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('seed', '種'), ('word_add', '語追加'), ('word_del', '語削除'), ('kire', '切れ'), ('imagery', '造形'), ('note', 'メモ')], max_length=16)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves', to='compose.draft')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='compose.session')),
            ],
        ),
        migrations.AddField(
            model_name='draft',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='compose.session'),
        ),
    ]
